### ISSUE TITLE
Add getRandomAddress and getRandomHexString functions

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/core-utils#37]
**Is your feature request related to a problem? Please describe.**
Add `getRandomAddress` and `getRandomHexString` functions. These are relatively common in the codebase and would be good to have them here.

**Describe the solution you'd like**
`getRandomHexString` should have the following function signature:

```ts
const getRandomHexString = (byteLength: number): string => { ... }
```

`getRandomHexString` should return "0x" followed by `byteLength` random hex bytes.

`getRandomAddress` should have the following function signature:

```ts
const getRandomAddress = (): string => { ... }
```

`getRandomAddress` can probably just be a call to `getRandomHexString(20)` wrapped in a call to `ethers.utils.getAddress`  in order to standardize the address.

**Additional context**
See here for inspiration: https://github.com/ethereum-optimism/smock/blob/main/src/utils/address-utils.ts#L3-L12

**Comment by bstchow** [comment]
I'd like to take a crack at this. @smartcontracts any opposition to replacing the `makeRandomAddress` function with the new `getRandomAddress` function?
