### ISSUE TITLE
Possibly misnamed variable

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/core-utils#5]
Should this be `shouldStartAtElement`?

https://github.com/ethereum-optimism/core-utils/blob/98ef6e0f6b4b237c894b95b7e00153f889819e80/src/coders/sequencer-batch.ts#L14

**Comment by platocrat** [comment]
> Should this be `shouldStartAtElement`?
> 
> https://github.com/ethereum-optimism/core-utils/blob/98ef6e0f6b4b237c894b95b7e00153f889819e80/src/coders/sequencer-batch.ts#L14

This has been patched with #8 

see https://github.com/ethereum-optimism/core-utils/blob/d4dcc4f598190f8c29261c5fcc78d9670c45b66e/src/coders/sequencer-batch.ts#L14

**Comment by tynes** [comment]
It should be `shouldStartAtElement`, the old name was `shouldStartAtBatch` which is misleading

**Comment by tynes** [comment]
Closing as this has been fixed - please reopen if there is an issue still
